spring:
  datasource:
    url: jdbc:mysql://a304.site:3306/mozzi
    username: ssafy
    password: ssafy
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  profiles:
    active: dev
security:
  jwt:
    secret-key: tlqkrtprtmtprtmtprtmtprtmtprtmtprtmtprtmtprtm
